POST http://localhost:3001/api/notes 
Content-Type: application/json


{
    "content": "prueba dos desde vsCode",
    "important": false
}
###
PUT  http://localhost:3001/api/notes/6425c076b5a0e493028a5178
Content-Type: application/json

{
    "content": "HTML is easy",
    "important": false 
}